#! /bin/sh

. "$PLAYPEN_ROOT/ext/libexec/functions/configurable-functions"

configurable_source --once libexec/functions/debug-hook
configurable_source --once libexec/functions/wigwam-base-functions
configurable_source --once libexec/environment/functions

if test "x$WIGWAM_INTERACTIVE_PID" = "x"
  then
    wigwam_base_fatal "$0: can't unset: missing WIGWAM_INTERACTIVE_PID" 
    exit 1
  fi

# Figure out what kind of shell the target script will be
# eval'd by.

unsetup_environment_shell_spec=""
unsetup_environment_zero_hack=""

while test "$#" -gt 0 
  do
    case "$1" in
      --shell)
        # if ! defined $2
        unsetup_environment_shell_spec="$2"
        test $# -eq 1 || shift

        ;;
      --shell=*)
        unsetup_environment_shell_spec=`echo $1 | sed -e 's/--shell=//'`

        ;;
      --0-hack)
        # if ! defined $2
           test $# -eq 1        \
        &&                      \
          {
            wigwam_base_fatal "$0: missing 0-hack spec" 
            exit 1
          }
        unsetup_environment_zero_hack="$2"
        shift

        ;;
      --0-hack=*)
        unsetup_environment_zero_hack=`echo $1 | sed -e 's/--0-hack=//'`
        ;;
      *)
        wigwam_base_fatal "$0: unexpected option $1" 
        exit 1

        ;;
    esac
    shift
  done

case "$unsetup_environment_shell_spec" in
  *csh)
    unsetup_environment_shell_style=csh
    ;;
  *sh)
    unsetup_environment_shell_style=sh
    ;;
  '') 
    case "$unsetup_environment_zero_hack" in
      0 | 1)
        unsetup_environment_shell_style=csh
        ;;
      [0-9]*0)
        unsetup_environment_shell_style=sh
        ;;
      '')
        unsetup_environment_shell_style=sh
        ;;
      *)
        wigwam_base_fatal "--0-hack got unexpected value"       \
                          "$unsetup_environment_zero_hack"
        exit 1
      ;;
    esac
    ;;
  *)
    wigwam_base_warn "print-interactive-environment:"           \
      "unrecognized shell spec '$unsetup_environment_shell_spec', assuming sh"
    unsetup_environment_shell_style=sh
    ;;
esac


unsetup_environment_unsetup_file="$PLAYPEN_ROOT/ext/tmp/unsetup-image-$WIGWAM_INTERACTIVE_PID"

if test -r "$unsetup_environment_unsetup_file"
  then
    for x in `configurable_run libexec/environment/ww-env-diffs         \
                --load-before="$unsetup_environment_unsetup_file"       \
                --list-new -- @all -_`
      do 
        ww_output_unset "$x" "$unsetup_environment_shell_style"
      done

    unsetup_environment_changed_vars=`configurable_run                  \
        libexec/environment/ww-env-diffs                                \
        --load-before="$unsetup_environment_unsetup_file"               \
        --list-modified --list-deleted -- @all -_`

    eval `configurable_run libexec/environment/ww-env-diffs             \
                --load-before="$unsetup_environment_unsetup_file"       \
                --print-undo -- @all -_`

    for x in $unsetup_environment_changed_vars
      do
        ww_output_int "$x" "$unsetup_environment_shell_style"
      done

    exit $?
  else
    wigwam_base_fatal "$0: can't find unsetup-image"        \
                      "for pid $WIGWAM_INTERACTIVE_PID"

    exit 1
  fi
