#! /bin/sh

. ../functions

. ./test_functions

foo=""
ww_app_grep foo foo :
compare "$foo" "foo"

ww_app_grep foo bar :
compare "$foo" "foo:bar"

ww_app_grep foo foo :
compare "$foo" "foo:bar"

ww_app_grep foo foo:bar:baz :
compare "$foo" "foo:bar:foo:bar:baz"

ww_app_grep foo bar:foo :
compare "$foo" "foo:bar:foo:bar:baz"

foo=""
ww_app_grep foo "taco plex dude" ' '
compare "$foo" "taco plex dude"

ww_app_grep foo "taco bar dude" ' '
compare "$foo" "taco plex dude taco bar dude"

ww_app_grep foo "dude taco" ' '
compare "$foo" "taco plex dude taco bar dude"
