#! /bin/sh

. ../functions

. ./test_functions

foo=""
ww_pre_grep foo foo :
compare "$foo" "foo"

ww_pre_grep foo bar :
compare "$foo" "bar:foo"

ww_pre_grep foo foo :
compare "$foo" "bar:foo"

ww_pre_grep foo foo:bar:baz :
compare "$foo" "foo:bar:baz:bar:foo"

ww_pre_grep foo bar:foo :
compare "$foo" "foo:bar:baz:bar:foo"

foo=""
ww_pre_grep foo "taco plex dude" ' '
compare "$foo" "taco plex dude"

ww_pre_grep foo "taco bar dude" ' '
compare "$foo" "taco bar dude taco plex dude"

ww_pre_grep foo "dude taco" ' '
compare "$foo" "taco bar dude taco plex dude"
